#!/usr/bin/env python3
"""
Neofetch Frame Converter
Converts ASCII art frames to neofetch-compatible format
"""

import os
import sys
import glob
from pathlib import Path

def convert_ascii_to_neofetch_frame(input_folder, output_folder, frame_prefix="frame"):
    """
    Convert ASCII art text files to neofetch frame format.
    
    Our ASCII converter already outputs the correct ANSI format!
    We just need to:
    1. Read the .txt files from ascii_converter output
    2. Rename them to frame0001.txt, frame0002.txt, etc.
    3. Save to neofetch frames_colour folder
    
    Args:
        input_folder: Folder containing ASCII .txt files
        output_folder: Output folder (e.g., ~/.config/neofetch/frames_colour/)
        frame_prefix: Prefix for frame files (default: "frame")
    """
    
    # Create output folder
    os.makedirs(output_folder, exist_ok=True)
    
    # Get all .txt files from input folder
    txt_files = sorted(glob.glob(os.path.join(input_folder, "*.txt")))
    
    if not txt_files:
        print(f"❌ No .txt files found in {input_folder}")
        return False
    
    print(f"\n{'='*60}")
    print(f"CONVERTING {len(txt_files)} FRAMES TO NEOFETCH FORMAT")
    print(f"{'='*60}")
    print(f"Input:  {input_folder}")
    print(f"Output: {output_folder}")
    print(f"{'='*60}\n")
    
    # Convert each file
    for i, txt_file in enumerate(txt_files, start=1):
        # Read the ASCII art (already has ANSI color codes!)
        with open(txt_file, 'r', encoding='utf-8') as f:
            ascii_art = f.read()
        
        # Generate output filename: frame0001.txt, frame0002.txt, etc.
        output_filename = f"{frame_prefix}{i:04d}.txt"
        output_path = os.path.join(output_folder, output_filename)
        
        # Write to output
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(ascii_art)
        
        print(f"✓ {os.path.basename(txt_file)} → {output_filename}")
    
    print(f"\n{'='*60}")
    print(f"✓ COMPLETE! {len(txt_files)} frames converted")
    print(f"{'='*60}\n")
    print("Next steps:")
    print("1. Backup your current frames:")
    print(f"   mv ~/.config/neofetch/frames_colour ~/.config/neofetch/frames_colour.backup")
    print("2. Copy new frames:")
    print(f"   cp -r {output_folder} ~/.config/neofetch/frames_colour")
    print("3. Clear neofetch cache:")
    print("   rm -f ~/.cache/neofetch.txt")
    print("4. Open new terminal to see your custom animation!")
    print()
    
    return True


def batch_convert_ascii_frames(input_folder, neofetch_frames_folder=None):
    """
    Batch convert ASCII frames from our GUI output.
    
    Expects input folder structure from ascii_converter GUI:
    - input_folder/*.txt (ASCII art with ANSI codes)
    
    Args:
        input_folder: Folder with ASCII .txt files from our converter
        neofetch_frames_folder: Where to save frames (default: ~/.config/neofetch/frames_colour)
    """
    
    if neofetch_frames_folder is None:
        neofetch_frames_folder = os.path.expanduser("~/.config/neofetch/frames_colour")
    
    return convert_ascii_to_neofetch_frame(input_folder, neofetch_frames_folder)


def create_from_gui_output(gui_output_folder, animation_name=None):
    """
    Create neofetch frames from GUI ASCII converter output.
    
    The GUI saves frames like:
    - cactusbubble_frame001_ascii.txt
    - cactusbubble_frame002_ascii.txt
    
    We need to convert them to:
    - frame0001.txt
    - frame0002.txt
    
    Args:
        gui_output_folder: Folder containing the ASCII .txt files
        animation_name: Name for the animation (creates subfolder)
    """
    
    # If animation name provided, create subfolder
    if animation_name:
        output_folder = os.path.expanduser(f"~/.config/neofetch/frames_{animation_name}")
    else:
        output_folder = os.path.expanduser("~/.config/neofetch/frames_colour")
    
    return batch_convert_ascii_frames(gui_output_folder, output_folder)


if __name__ == "__main__":
    print("\n" + "="*60)
    print("NEOFETCH FRAME CONVERTER")
    print("Convert ASCII art frames to neofetch-compatible format")
    print("="*60 + "\n")
    
    if len(sys.argv) < 2:
        print("Usage:")
        print(f"  {sys.argv[0]} <input_folder> [output_folder]")
        print()
        print("Examples:")
        print(f"  {sys.argv[0]} ./ascii_output")
        print(f"  {sys.argv[0]} ./ascii_frames ~/.config/neofetch/frames_colour")
        print()
        print("The input folder should contain .txt files with ASCII art")
        print("(generated by our ASCII converter)")
        print()
        sys.exit(1)
    
    input_folder = sys.argv[1]
    
    if len(sys.argv) >= 3:
        output_folder = sys.argv[2]
    else:
        output_folder = os.path.expanduser("~/.config/neofetch/frames_colour")
    
    # Check if input folder exists
    if not os.path.exists(input_folder):
        print(f"❌ Error: Input folder not found: {input_folder}")
        sys.exit(1)
    
    # Convert frames
    success = convert_ascii_to_neofetch_frame(input_folder, output_folder)
    
    if success:
        print("🎉 Success! Your custom neofetch animation is ready!")
    else:
        print("❌ Conversion failed!")
        sys.exit(1)